# Generated by Django 3.2.23 on 2024-02-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_min',
            new_name='time_minutes',
        ),
    ]
